name: Anki arm64 builder

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup qemu binfmt
        run: sudo apt-get -y install qemu binfmt-support qemu-user-static

      - name: Build Anki
        run: docker run --platform linux/arm64 -v ${PWD}:/anki-arm64 fedora:34 bash /anki-arm64/build.sh
